# Generated by Django 5.2.3 on 2025-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='file',
        ),
        migrations.AddField(
            model_name='presentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/pdf/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='pptx_file',
            field=models.FileField(default='', upload_to='presentations/pptx/'),
            preserve_default=False,
        ),
    ]
