# Generated by Django 5.2.3 on 2025-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_presentation_file_presentation_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/pptx/'),
        ),
    ]
