# Generated by Django 5.2.3 on 2025-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_presentation_pptx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pptx_file',
            field=models.FileField(default='', upload_to='presentations/pptx/'),
            preserve_default=False,
        ),
    ]
