# Generated by Django 5.2.3 on 2025-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_presentation_pptx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/pptx/'),
        ),
    ]
